### ISSUE TITLE
Is this still maintained anywhere?

### ISSUE THREAD

**Issue by tylers-username** [crisu83/php-conversion#21]

**Comment by cniska** [comment]
Yes, is there something you need?

**Comment by tylers-username** [comment]
The package looks very promising and I am hoping to find the latest stable version. I noticed that this repository was last updated in May of 2016 and I do not know if that is because it's in a stable state and requires no maintenance or if it's been abandoned and there is a fork available elsewhere.

**Comment by ojhaujjwal** [comment]
@crisu83 and I are maintainers. If you have any significant issues, you can create an issue. we will look into it.
if you have found the solution to any issues, you can always open PR, we will review the PR as soon as it's feasible for us. 

I don't think you can find any thing more from an apparently un-updated library!
